import Sidebar from "@/components/Sidebar";
import { ExpressManagerProvider } from "@/context/ExpressManagerContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
  <ExpressManagerProvider>
    <div className="flex min-h-screen bg-[#f7f8fb]">
      <Sidebar />
      <div className="flex-1">
        {children}
      </div>
    </div>
  </ExpressManagerProvider>
</body>
    </html>
  );
}
